apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.fullname" . }}-apiserver
  labels:
    app: {{ template "kubernetes.name" . }}-apiserver
    chart: {{ template "kubernetes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.apiserver.service.type }}
{{- if .Values.apiserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.apiserver.service.loadBalancerIP }}
{{- end }}
{{- if .Values.apiserver.service.clusterIP }}
  clusterIP: {{ .Values.apiserver.service.clusterIP }}
{{- end }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ template "kubernetes.name" . }}-apiserver
    release: {{ .Release.Name }}
