---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetes.fullname" . }}
  labels:
    app: {{ template "kubernetes.name" . }}
    chart: {{ template "kubernetes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "scripts/make-ca-cert.sh").AsConfig | indent 2 }}
